---
volumes:
  db_data:

services:
  app:
    image: mieweb_auth_app:latest
    deploy:
      replicas: 3
    environment:
      MONGO_URL: mongodb://mongodb:27017/mieweb_auth_app
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - db_data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:Z
    depends_on:
      - app
